1.  0부터 9까지의 숫자가 순서대로 하나씩 들어있는 1차원 배열을 생성하는 코드를 작성하시오

 

2. 모든 요소가 True 로 채워진 (3, 3) 의 형상을 가지는 다차원 배열을 생성하는 코드를 작성하시오

 

3. 랜덤한 값으로 채워진 (3, 3, 3) 의 형상을 가지는 다차원 배열을 생성하는 코드를 작성하시오

 

4. 바깥쪽 테두리에는 1이 채워져 있고 내부는 0으로 채워진 (10, 10) 형상의 2차원 배열을 생성하는 코드를 작성하시오

 

5. (8, 8) 형상의 2차원 배열을 0과 1을 번갈아가며 채워 생성하는 코드를 작성하시오

예)

0, 1, 0, 1

1, 0, 1, 0

0, 1, 0, 1

1, 0, 1, 0

In [1]:
import numpy as np

In [2]:
# 1.  0부터 9까지의 숫자가 순서대로 하나씩 들어있는 1차원 배열을 생성하는 코드를 작성하시오

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 2. 모든 요소가 True 로 채워진 (3, 3) 의 형상을 가지는 다차원 배열을 생성하는 코드를 작성하시오

np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# 3. 랜덤한 값으로 채워진 (3, 3, 3) 의 형상을 가지는 다차원 배열을 생성하는 코드를 작성하시오

np.random.random((3, 3, 3))

array([[[0.73215483, 0.91863776, 0.41652467],
        [0.29208897, 0.47290819, 0.55406433],
        [0.89731906, 0.98434558, 0.86798992]],

       [[0.1109484 , 0.1204547 , 0.69827314],
        [0.6752167 , 0.13872472, 0.65681481],
        [0.61438138, 0.71592297, 0.71345928]],

       [[0.11505743, 0.77688919, 0.56286114],
        [0.36244817, 0.92607137, 0.79400123],
        [0.94354833, 0.48748787, 0.78956988]]])

In [19]:
# 4. 바깥쪽 테두리에는 1이 채워져 있고 내부는 0으로 채워진 (10, 10) 형상의 2차원 배열을 생성하는 코드를 작성하시오

array4 = np.ones((10, 10), int)
array4

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [20]:
for i in range(1, 9):
    for j in range(1, 9):
        array4[i][j] = 0
        
array4

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

[ 조건 만족 시 출력값 if 조건 else 조건 불만족 시 출력 값 for i in data] 

In [33]:
np.array([0 if 0 < i < 9 and  0 < j < 9 else 1 for i in range(0, 10) for j in range(0, 10)]).reshape(10, 10)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
# 5. (8, 8) 형상의 2차원 배열을 0과 1을 번갈아가며 채워 생성하는 코드를 작성하시오

np.array([(i+j)%2 for i in range(0, 8) for j in range(0, 8)]).reshape(8, 8)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [29]:
np.array([(i+j)%2 for i in range(0, 8) for j in range(0, 8)]).reshape(8, 8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

1. arr = np.arange(10) 이라고 할 때 arr 에서 홀수들만 추출하여 출력하시오

 

2. arr = np.arange(10) 에서 홀수들을 -1로 수정하여 출력하시오

예) [0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

 

3. 배열 a와 b가 아래와 같을 때, a와 b의 요소 중 동일한 인덱스에 동일한 값이 들어있는 요소들만 추출하여 출력하시오

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

예) array([2, 2, 4, 4])

 

4. a = np.array([2, 6, 1, 9, 10, 3, 27]) 라고 할 때 5이상 10이하인 값만 추출하여 출력하시오

 

5. arr = np.arange(9).reshape(3,3) 라고 할 때 arr의 첫 번째 컬럼과 두 번째 컬럼의 순서를 바꾸어 출력하시오

예) array([[1, 0, 2],       [4, 3, 5],       [7, 6, 8]])

 

6. arr = np.arange(9).reshape(3,3) 라고 할 때 행의 순서를 반대로 바꾸어 출력하시오

예) array([[6, 7, 8],       [3, 4, 5],       [0, 1, 2]])

In [36]:
np.arange(10)%2 == 1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [71]:
# 1. arr = np.arange(10) 이라고 할 때 arr 에서 홀수들만 추출하여 출력하시오

arr = np.arange(10)
arr[arr%2 == 1]
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
# 2. arr = np.arange(10) 에서 홀수들을 -1로 수정하여 출력하시오

arr = np.arange(10)
arr = np.where(arr%2 == 1, -1, arr)
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [73]:
# 3. 배열 a와 b가 아래와 같을 때, a와 b의 요소 중 동일한 인덱스에 동일한 값이 들어있는 요소들만 추출하여 출력하시오

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

a[np.array([i in b for i in a])]

array([2, 2, 4, 4])

In [75]:
# 4. a = np.array([2, 6, 1, 9, 10, 3, 27]) 라고 할 때 5이상 10이하인 값만 추출하여 출력하시오

a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a <= 10) & (a >= 5)]

array([ 6,  9, 10])

In [ ]:
#5. arr = np.arange(9).reshape(3,3) 라고 할 때 arr의 첫 번째 컬럼과 두 번째 컬럼의 순서를 바꾸어 출력하시오

예) array([[1, 0, 2],       [4, 3, 5],       [7, 6, 8]])

In [76]:
arr = np.arange(9).reshape(3,3)

for i in range(0, 3):
    arr[i][0], arr[i][1] = arr[i][1], arr[i][0]
    
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [77]:
# arr = np.arange(10) 이라고 할 때
# arr을 2개의 행을 갖는 2차원 배열로 형상을 변경하시오

arr = np.arange(10)

arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

다차원배열 arr 가 아래와 같다고 할 때

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

 

아래의 지시사항에 따라 연산을 수행하는 코드를 작성하시오

 

1. 각 2차원 배열의 각 행의 평균값을 계산하시오

 

2. 각 2차원 배열의 합을 계산하시오

 

3. 각 2차원 배열의 각 열의 표준편차를 계산하시오

In [79]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [80]:
# 1. 각 2차원 배열의 각 행의 평균값을 계산하시오

arr.mean(axis = 2)

array([[ 2.,  5.],
       [ 8., 11.],
       [14., 17.]])

In [81]:
# 2. 각 2차원 배열의 합을 계산하시오

arr.sum(axis = (1, 2))

array([21, 57, 93])

In [82]:
# 3. 각 2차원 배열의 각 열의 표준편차를 계산하시오

arr.std(axis = 1)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

배열 arr이 아래와 같을 때, 아래의 지시사항에 따라 데이터 전처리를 수행하는 코드를 작성하시오

arr = np.arange(1, 9).reshape(4, 2)

 

1. 각 열의 값이 최솟값이 0, 최댓값이 1이 될 수 있도록 정규화를 하려고 한다

정규화의 공식이 ((각 요소 값 - 해당 열의 최솟값) / (해당 열의 최댓값 - 해당 열의 최솟값)) 이라고 할 때

위의 공식에 따라 정규화를 수행하면 결과는 

array([[0.        , 0.        ],       [0.33333333, 0.33333333],       [0.66666667, 0.66666667],       [1.        , 1.        ]]) 이 된다

arr을 위의 공식에 따라 정규화를 수행하는 코드를 작성하시오

 

2. 각 행 내에서 해당 요소가 차지하는 비율로 값을 수정하려고 한다

정규화의 공식이 (각 요소 값 / 해당 행의 합) 이라고 할 때

하나의 행이 [2, 3] 으로 구성되어 있다면 해당 행에서 2가 차지하는 비중은 0.4, 3이 차지하는 비중은 0.6으로 변환된다

arr을 위의 공식에 따라 정규화를 수행하는 코드를 작성하시오

In [100]:
# 1. 각 열의 값이 최솟값이 0, 최댓값이 1이 될 수 있도록 정규화를 하려고 한다

arr = np.arange(1, 9).reshape(4, 2)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [89]:
arr_min = arr.min(axis = 0)
arr_max = arr.max(axis = 0)

In [149]:
np.array((arr - arr_min) / (arr_max - arr_min))

array([[0.        , 0.        ],
       [0.33333333, 0.33333333],
       [0.66666667, 0.66666667],
       [1.        , 1.        ]])

In [112]:
# 2. 각 행 내에서 해당 요소가 차지하는 비율로 값을 수정하려고 한다

arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [115]:
# 2. 각 행 내에서 해당 요소가 차지하는 비율로 값을 수정하려고 한다

np.array([i / i.sum() for i in arr])

array([[0.33333333, 0.66666667],
       [0.42857143, 0.57142857],
       [0.45454545, 0.54545455],
       [0.46666667, 0.53333333]])

arr = np.arange(2 * 3 * 4).reshape((2, 3, 4)) 라고 할 때

 

1. array([[14, 15],       [18, 19],       [22, 23]]) 를 슬라이싱하는 코드를 작성하시오

 

2. array([[ 2,  6, 10],       [14, 18, 22]]) 를 슬라이싱하는 코드를 작성하시오

 

3. array([[ 1,  5,  9],       [13, 17, 21]]) 를 슬라이싱하는 코드를 작성하시오

In [116]:
arr = np.arange(2 * 3 * 4).reshape((2, 3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [117]:
# 1. array([[14, 15],       [18, 19],       [22, 23]]) 를 슬라이싱하는 코드를 작성하시오

arr[1, :, 2:]

array([[14, 15],
       [18, 19],
       [22, 23]])

In [121]:
# 2. array([[ 2,  6, 10],       [14, 18, 22]]) 를 슬라이싱하는 코드를 작성하시오

arr[:, :, 2]

array([[ 2,  6, 10],
       [14, 18, 22]])

In [122]:
# 3. array([[ 1,  5,  9],       [13, 17, 21]]) 를 슬라이싱하는 코드를 작성하시오

arr[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [123]:
import numpy as np

In [124]:
# 1.  0부터 9까지의 숫자가 순서대로 하나씩 들어있는 1차원 배열을 생성하는 코드를 작성하시오



np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
# 2. 모든 요소가 True 로 채워진 (3, 3) 의 형상을 가지는 다차원 배열을 생성하는 코드를 작성하시오



np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [126]:
# 3. 랜덤한 값으로 채워진 (3, 3, 3) 의 형상을 가지는 다차원 배열을 생성하는 코드를 작성하시오



np.random.random((3, 3, 3))

array([[[0.03448174, 0.41337829, 0.91870072],
        [0.83638449, 0.86062279, 0.59730124],
        [0.18555993, 0.30799358, 0.12113124]],

       [[0.70027604, 0.34570121, 0.84048542],
        [0.41660187, 0.5864387 , 0.42082838],
        [0.28550403, 0.80577144, 0.64940151]],

       [[0.1984776 , 0.82183244, 0.65337632],
        [0.83186959, 0.35456497, 0.3120735 ],
        [0.55750527, 0.18773527, 0.01180645]]])

In [127]:
# 4. 바깥쪽 테두리에는 1이 채워져 있고 내부는 0으로 채워진 (10, 10) 형상의 2차원 배열을 생성하는 코드를 작성하시오



np.array([0 if 0 < i < 9 and  0 < j < 9 else 1 for i in range(0, 10) for j in range(0, 10)]).reshape(10, 10)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [128]:
# 5. (8, 8) 형상의 2차원 배열을 0과 1을 번갈아가며 채워 생성하는 코드를 작성하시오



np.array([(i+j)%2 for i in range(0, 8) for j in range(0, 8)]).reshape(8, 8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [130]:
# 1. arr = np.arange(10) 이라고 할 때 arr 에서 홀수들만 추출하여 출력하시오

arr = np.arange(10)


arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [131]:
# 2. arr = np.arange(10) 에서 홀수들을 -1로 수정하여 출력하시오

arr = np.arange(10)


arr = np.where(arr%2 == 1, -1, arr)
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [136]:
# 3. 배열 a와 b가 아래와 같을 때, a와 b의 요소 중 동일한 인덱스에 동일한 값이 들어있는 요소들만 추출하여 출력하시오

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])



a[[i in b for i in a]]

array([2, 2, 4, 4])

In [137]:
# 4. a = np.array([2, 6, 1, 9, 10, 3, 27]) 라고 할 때 5이상 10이하인 값만 추출하여 출력하시오

a = np.array([2, 6, 1, 9, 10, 3, 27])



a[(a <= 10) & (a >= 5)]

array([ 6,  9, 10])

In [138]:
#5. arr = np.arange(9).reshape(3,3) 라고 할 때 arr의 첫 번째 컬럼과 두 번째 컬럼의 순서를 바꾸어 출력하시오

arr = np.arange(9).reshape(3,3)



for i in range(0, 3):
   arr[i][0], arr[i][1] = arr[i][1], arr[i][0]
   
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [139]:
arr = np.arange(10)

arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [141]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

arr



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [142]:
# 1. 각 2차원 배열의 각 행의 평균값을 계산하시오



arr.mean(axis = 2)

array([[ 2.,  5.],
       [ 8., 11.],
       [14., 17.]])

In [143]:
# 2. 각 2차원 배열의 합을 계산하시오



arr.sum(axis = (1, 2))

array([21, 57, 93])

In [144]:
# 3. 각 2차원 배열의 각 열의 표준편차를 계산하시오



arr.std(axis = 1)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [145]:
arr = np.arange(1, 9).reshape(4, 2)

In [146]:
# 1. 각 열의 값이 최솟값이 0, 최댓값이 1이 될 수 있도록 정규화를 하려고 한다

arr_min = arr.min(axis = 0)
arr_max = arr.max(axis = 0)

np.array([(i - arr_min) / (arr_max - arr_min) for i in arr])

array([[0.        , 0.        ],
       [0.33333333, 0.33333333],
       [0.66666667, 0.66666667],
       [1.        , 1.        ]])

In [147]:
# 2. 각 행 내에서 해당 요소가 차지하는 비율로 값을 수정하려고 한다



np.array([i / i.sum() for i in arr])

array([[0.33333333, 0.66666667],
       [0.42857143, 0.57142857],
       [0.45454545, 0.54545455],
       [0.46666667, 0.53333333]])