In [1]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array; 다차원배열)

In [2]:
# 리스트를 다차원배열로 변환
# array() : 다차원 배열을 만드는 함수
li = [1, 2, 3, 4]
li_arr = np.array(li)

In [3]:
li_arr

array([1, 2, 3, 4])

In [4]:
type(li_arr)

numpy.ndarray

In [5]:
# 튜플을 다차원배열로 변환
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [6]:
tu_arr

array([1, 2, 3, 4])

In [7]:
type(tu_arr)

numpy.ndarray

In [8]:
# 배열도 mutable의 특징을 가짐
# 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨
co_arr = li_arr
id(co_arr), id(li_arr)

(1868393659440, 1868393659440)

In [9]:
co_arr[0] = 100
co_arr

array([100,   2,   3,   4])

In [10]:
li_arr

array([100,   2,   3,   4])

In [11]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열을을 만들기 때문에 서로 다른 데이터가 됨
new_arr = np.array(li_arr)

In [12]:
id(new_arr), id(li_arr)

(1868388852208, 1868393659440)

In [13]:
new_arr[0] = 99
new_arr

array([99,  2,  3,  4])

In [14]:
li_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
     - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

In [15]:
# float 자료형을 지정해서 다차원 배열을 만들기
fl_arr = np.array(li, dtype = float)
fl_arr

array([1., 2., 3., 4.])

In [16]:
fl_arr.dtype

dtype('float64')

## 2차원 배열

- 2개의 축을 가지는 배열(행, 열)
    - 두 개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [18]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2d.shape

(2, 3)

In [20]:
# 축의 개수
arr2d.ndim

2

In [21]:
arr2d.dtype

dtype('int32')

In [22]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

## 원소 조회하기

In [23]:
# 1차원 배열에서 원소 조회
li_arr

array([100,   2,   3,   4])

In [24]:
li

[1, 2, 3, 4]

In [25]:
li_arr[0]

100

In [26]:
li[0]

1

In [27]:
# 다차원 배열에서 원소 조회
list2d = arr2d.tolist() # 배열을 리스트로 변환

In [28]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [29]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱스를 두 번 사용해야 함
list2d[0][1]

2

In [31]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

2

In [32]:
arr2d[0][1]

2

## 슬라이싱

In [33]:
arr1 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
# 첫 번째 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [37]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [38]:
# 두 번째 행의 두 번째 열부터 끝열까지
arr1[1, 1:]

array([5, 6, 7])

In [39]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

#### 연습문제

1. 아래의 행렬에서 값 7을 인덱싱
2. 아래의 행력에서 값 14를 인덱싱
3. 아래의 행렬에서 배열 [6, 7]을 슬라이싱
4. 아래의 행렬에서 배열 [7, 12]를 슬라이싱
5. 아래의 행렬에서 배열 [[3. 4], [8, 9]]를 슬라이싱

In [40]:
m = np.array([[0, 1, 2, 3, 4],
             [5, 6, 7 ,8 ,9],
             [10, 11, 12, 13, 14]])

In [41]:
m[1, 2]

7

In [42]:
m[2, -1]

14

In [43]:
m[1, 1:3]

array([6, 7])

In [44]:
m[1:, 2]

array([ 7, 12])

In [48]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [49]:
m = np.array([[[1, 2, 3], [4, 5, 6]],
           [[7, 8, 9], [10, 11, 12]],
             [[13, 14, 15], [16, 17, 18]],
             [[19, 20, 21], [22, 23, 24]]])

1. [8, 14] 슬라이싱
2. [[11, 12], [17, 18]] 슬라이싱
3. [3, 9, 15, 21] 슬라이싱

In [55]:
m[1:3, 0, 1]

array([ 8, 14])

In [52]:
m[1:3, 1, 1:]

array([[11, 12],
       [17, 18]])

In [54]:
m[:, 0, 2]

array([ 3,  9, 15, 21])

## 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능
- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
    - 파이썬 리스트 : 곱셈으로 리스트를 반복하는 것은 가능
    
- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
    - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원 배열이 필요할 때 사용

# 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# 배열 크기 변형

In [4]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr2 = arr1.reshape(3, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
# 수가 안맞으면 에러 발생
arr1.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소 중 하나는 -1로 대체할 수 있음

In [9]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [12]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# 넘파이 함수의 특징

- 벡터화 연산
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인데긋의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함
    
- 유니버설 함수 (universal function)
    - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [13]:
# 일반 파이썬 함수의 타입 확인
def test():
    pass

In [15]:
type(test)

function

In [16]:
# 유니버설 함수 확인
type(np.add)

numpy.ufunc

In [17]:
# 넘파이 모듈에는 유니버설 함수도 있고 일반 함수도 있음
type(np.sort)

function

In [18]:
list2d = [[1, 2, 3], [4, 5, 6]]

In [19]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [20]:
np.add(list2d, list2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산

### 벡터화 연산이 필요한 이유

- data 리스트 내의 각 값에 2를 곱해야 하는 이유

In [22]:
# 리스트를 통한 풀이
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
ans = []

for i in data:
    ans.append(i * 2)
    
ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [25]:
# 넘파이를 통한 풀이
data = np.array(data)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [27]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [28]:
2 * a + b

array([12, 24, 36])

In [29]:
a == 2

array([False,  True, False])

In [30]:
[1 ,2, 3] == 2

False

In [31]:
b > 10

array([False,  True,  True])

In [34]:
(a == 2) & (b > 10)

array([False,  True, False])

In [35]:
(a == 2) | (b > 10)

array([False,  True,  True])

In [36]:
a[[True, False, True]]

array([1, 3])

In [37]:
a[a == 2]

array([2])

- 배열끼리의 연산

In [38]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [39]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [40]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셉한 결과인 1차원 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [43]:
# arr1에 차원 추가 (수직축 추가)
new_arr1 = arr1.reshape(-1, 1)
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [44]:
new_arr1.shape

(4, 1)

In [45]:
# arr2에 차원 추가 (수평축 추가)
new_arr2 = arr2.reshape(1, -1)
new_arr2

array([[10, 11, 12, 13]])

In [46]:
new_arr2.shape

(1, 4)

## 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야함
- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복확장하여 크기가 큰 배열에 맞춤

In [47]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

In [48]:
# 행렬곱 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [49]:
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [50]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [51]:
a

array([[1, 2],
       [3, 4]])

In [52]:
b

array([[5, 6],
       [7, 8]])

In [53]:
# * 연산자는 요소별 곱셈을 수행
a * b

array([[ 5, 12],
       [21, 32]])

In [54]:
# @ 연산자는 행렬 곱셈을 수행
a @ b

array([[19, 22],
       [43, 50]])

#### 연습문제

1. 아래의 배열에서 3의 배수를 찾기
2. 아래의 배열에서 4로 나누면 1이 남는 수 찾기
3. 아래의 배열에서 3으로 나누면 나우어지고 4로 나누면 1이 남는 수 찾기

In [55]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
x[x%3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [58]:
x[x%4 == 1]

array([ 1,  5,  9, 13, 17])

In [60]:
x[(x%3 == 0) & (x%4 == 1)]

array([9])

## 축에 따른 연산

- 동일한 추겡 있는 원소들을 계산하기 위해 필요

In [61]:
# 1차원 배열
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [62]:
# 합계
np.sum(arr1)

10

In [63]:
arr1.sum()

10

In [64]:
arr1.max()

4

In [65]:
arr1.min()

1

In [68]:
# 최솟값의 위치를 반환
arr1.argmin()

0

In [67]:
# 최댓값의 위치를 반환
arr1.argmax()

3

In [69]:
arr1.mean()

2.5

In [70]:
# 중앙값
np.median(arr1)

2.5

In [71]:
arr1.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [72]:
# 2차원 배열
arr2 = arr1.reshape(2, 2)
arr2

array([[1, 2],
       [3, 4]])

In [73]:
# 모든 원소를 더한 합
np.sum(arr2)

10

In [74]:
# 수직 방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [75]:
# 수평 방향으로 같은 행에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [76]:
# 3차원 배열
arr3 = np.arange(1, 9)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
arr4 = arr3.reshape(2, 2, 2)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [78]:
# 모든 원소를 더한 합
arr4.sum()

36

In [82]:
np.sum(arr4, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [83]:
np.sum(arr4, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [84]:
np.sum(arr4, axis = 2)

array([[ 3,  7],
       [11, 15]])

In [87]:
np.sum(arr4, axis = (1, 2))

array([10, 26])

In [88]:
np.sum(arr4, axis = (0, 2))

array([14, 22])

In [89]:
np.sum(arr4, axis = (0, 1))

array([16, 20])

In [110]:
np.sum(arr4, axis = (0, 1, 2))

36

#### 연습문제

1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [90]:
x = np.random.random((5, 6))
x

array([[0.95961843, 0.5360596 , 0.16051881, 0.90749866, 0.28427379,
        0.7574049 ],
       [0.71360031, 0.16852242, 0.67484851, 0.99638305, 0.76329595,
        0.53794042],
       [0.41374795, 0.87097292, 0.59814211, 0.89540178, 0.58315618,
        0.59252997],
       [0.549327  , 0.23860589, 0.30408595, 0.64997292, 0.68265531,
        0.25822115],
       [0.65252293, 0.61331382, 0.39302811, 0.6170637 , 0.73361484,
        0.69625659]])

In [91]:
x.max()

0.9963830459601426

In [95]:
np.sum(x, axis = 1)

array([3.60537419, 3.85459065, 3.95395091, 2.68286823, 3.70579998])

In [96]:
np.max(x, axis = 1)

array([0.95961843, 0.99638305, 0.89540178, 0.68265531, 0.73361484])

In [104]:
np.mean(x, axis = 0)

array([0.65776332, 0.48549493, 0.4261247 , 0.81326402, 0.60939921,
       0.56847061])

In [98]:
np.min(x, axis = 0)

array([0.41374795, 0.16852242, 0.16051881, 0.6170637 , 0.28427379,
       0.25822115])

In [109]:
min([0.95961843, 0.71360031, 0.41374795, 0.549327, 0.65252293])

0.41374795

In [111]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [114]:
arr4.sum(axis = 0)

array([[ 6,  8],
       [10, 12]])

In [115]:
arr4.sum(axis = 1)

array([[ 4,  6],
       [12, 14]])

In [116]:
arr4.sum(axis = -1)

array([[ 3,  7],
       [11, 15]])

In [117]:
arr4.sum(axis = (0, 1))

array([16, 20])

In [118]:
arr4.sum(axis = (0, -1))

array([14, 22])

In [119]:
arr4.sum(axis = -1).sum(axis = -1)

array([10, 26])

In [120]:
arr5 = np.random.randint(0, 3, (2, 3, 4))
arr5

array([[[1, 2, 1, 0],
        [2, 0, 1, 0],
        [0, 2, 2, 0]],

       [[0, 1, 1, 1],
        [0, 2, 2, 0],
        [2, 1, 1, 2]]])

In [121]:
arr5.sum(axis = 0)

array([[1, 3, 2, 1],
       [2, 2, 3, 0],
       [2, 3, 3, 2]])

In [123]:
arr5.sum(axis = 1).shape

(2, 4)

In [124]:
arr5.sum(axis = 2).shape

(2, 3)

In [126]:
arr5.sum(axis = (0, 1)).shape

(4,)

In [127]:
arr5.sum(axis = (0, 2)).shape

(3,)

In [128]:
arr5.sum(axis = (1, 2)).shape

(2,)

In [129]:
data_3d = np.random.random((3, 5, 6))
data_3d

array([[[0.9033549 , 0.39718506, 0.52805558, 0.48389895, 0.22799708,
         0.63145202],
        [0.104881  , 0.33149798, 0.50071872, 0.73797236, 0.31217129,
         0.12689445],
        [0.56594668, 0.2918688 , 0.35841936, 0.94931597, 0.3256701 ,
         0.29104119],
        [0.19003272, 0.24678321, 0.18992478, 0.58050331, 0.32204626,
         0.96117716],
        [0.43209745, 0.19744177, 0.1260301 , 0.27431047, 0.38197605,
         0.63270215]],

       [[0.4652868 , 0.10552453, 0.20712765, 0.2806198 , 0.18965698,
         0.544366  ],
        [0.70598277, 0.73091818, 0.17537323, 0.38895499, 0.17380559,
         0.68271486],
        [0.03165775, 0.47261408, 0.67134882, 0.11765668, 0.33169598,
         0.22754604],
        [0.05919469, 0.43568606, 0.50888593, 0.62540745, 0.05145321,
         0.22871354],
        [0.7331327 , 0.0870542 , 0.96352594, 0.94851817, 0.66971571,
         0.53392569]],

       [[0.87384019, 0.23970074, 0.15860528, 0.74681985, 0.34475761,
         0.371496

1. 각 2차원 배열에서의 최댓값
2. 각 2차원 배열에서의 행의 합
3. 각 2차원 배열에서의 각 행의 최댓값
4. 전체 열의 평균
5. 각 2차원 배열에서의 열의 평균
6. 각 2차원 배열에서의 각 열의 최솟값

In [132]:
data_3d.max(axis = (1, 2))

array([0.96117716, 0.96352594, 0.95085544])

In [141]:
data_3d.max(axis = -1).max(axis = -1)

array([0.96117716, 0.96352594, 0.95085544])

In [134]:
data_3d.sum(axis = 2)

array([[3.17194359, 2.11413579, 2.78226209, 2.49046745, 2.04455799],
       [1.79258176, 2.85774962, 1.85251935, 1.90934088, 3.93587241],
       [2.73522035, 3.02130932, 2.11463918, 2.8652116 , 2.91882302]])

In [135]:
data_3d.max(axis = 2)

array([[0.9033549 , 0.73797236, 0.94931597, 0.96117716, 0.63270215],
       [0.544366  , 0.73091818, 0.67134882, 0.62540745, 0.96352594],
       [0.87384019, 0.95085544, 0.68072371, 0.94705707, 0.86574059]])

In [137]:
data_3d.mean(axis = (0, 1))

array([0.41997268, 0.41627976, 0.37531873, 0.52905564, 0.27074436,
       0.56240445])

In [136]:
data_3d.mean(axis = 1)

array([[0.43926255, 0.29295536, 0.34062971, 0.60520021, 0.31397216,
        0.52865339],
       [0.39905094, 0.36635941, 0.50525232, 0.47223142, 0.28326549,
        0.44345323],
       [0.42160456, 0.58952451, 0.28007417, 0.50973529, 0.21499542,
        0.71510673]])

In [138]:
data_3d.min(axis = 1)

array([[0.104881  , 0.19744177, 0.1260301 , 0.27431047, 0.22799708,
        0.12689445],
       [0.03165775, 0.0870542 , 0.17537323, 0.11765668, 0.05145321,
        0.22754604],
       [0.04593016, 0.23970074, 0.1399349 , 0.06814112, 0.05223729,
        0.37149667]])

# Inf와 nan
- 넘파이에서는 무한대를 표한하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan이 있음

In [142]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\ITSC\AppData\Local\Temp\ipykernel_7180\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\ITSC\AppData\Local\Temp\ipykernel_7180\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])