In [1]:
import numpy as np

# 스칼라와 벡터

- 벡터와 행렬은 특정 텐서(tensor)를 부르는 이름
- 텐서의 이름을 부여하는 원칙은 차원인 축(axis)를 기준으로 지정
    - 텐서가 0차원인 경우(축이 없는 경우) : 스칼라(scalar)
    - 1차원인 하나의 축을 가진 경우 : 벡터(vector)
    - 2차원인 2개의 축을 가진 경우 : 행렬(matrix)
    - 3차원인 3개의 축을 가진 경우 : 큐브(cube) 또는 3차원 텐서
    - 더 차원이 높은 경우는 차원을 기준으로는 n차원 텐서라고 부름

## 스칼라

- 0차원 배열
- 크기를 표현
- 가장 기본적인 값
- 수학에서 배운 정수나 실수는 하나의 물리량인 크기를 표현하는데, 이 값을 스칼라 라고 함

In [2]:
scalar_arr = np.array(43)

In [3]:
# array에서 스칼라는 대괄호 없이 숫자만 표시
# 대괄호는 벡터(1차원 배열)부터 사용
scalar_arr

array(43)

In [4]:
# 스칼라는 0차원
scalar_arr.ndim

0

In [5]:
scalar_arr.shape

()

In [6]:
# array로 스칼라를 만들어도 dtype을 가짐
scalar_arr.dtype

dtype('int32')

## 벡터

- 1차원 배열

In [7]:
vector = np.array([43])

In [8]:
vector

array([43])

In [9]:
type(vector)

numpy.ndarray

In [10]:
# 1차원 배열
vector.ndim

1

In [11]:
vector.shape

(1,)

## 배열생성함수

### zeros

- 크기가 정해져 있고 모든 값이 0인 배열 생성
- 인수로는 배열의 크기를 전달

In [12]:
# 1차원 배열
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [14]:
# 2차원 배열
zero_arr2 = np.zeros((2, 3))
zero_arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

- dtype 인수를 명시하면 해당 자료형 원소 배열을 생성

In [15]:
zero_arr3 = np.zeros((5, 2), dtype = int)
zero_arr3

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### ones

- 모든 값이 1인 배열 생성

In [18]:
one_arr = np.ones((2, 3, 4), dtype = int)
one_arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### zeros_like, ones_like

- 다른 배열과 같은 크기의 배열을 생성 (shape이 일치하는)
- 데이터 타입도 복사해온다

In [22]:
zero_arr4 = np.zeros_like(one_arr)
zero_arr4

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [23]:
zero_arr4 = np.zeros(one_arr.shape)
zero_arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
one_arr2 = np.ones_like(zero_arr3)
one_arr2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

### arange

- 파이썬의 range와 유사한 함수
- range와 같이 시작점, 종료점, 증감값을 인자로 전달
    - 종료점은 필수

In [27]:
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
vector.dtype

dtype('int32')

- np.arange()는 인자로 실수를 지정할 수 있음

In [30]:
vector1 = np.arange(10.5, 20.5, 0.5)
vector1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [31]:
vector1.dtype

dtype('float64')

In [32]:
# 원소의 개수
vector1.size

20

In [34]:
# 1차원 배열을 생성하면서 바로 2차원 배열로 형상 변경
vector2 = np.arange(60).reshape(6, 10)
vector2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [35]:
vector2.shape

(6, 10)

In [36]:
# 1차원 배열을 생성하면서 바로 3차원 배열로 형상 변경
vector3 = np.arange(60).reshape(3, 4, 5)
vector3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

### linspace

- arange와의 차이점
    - 종료점도 포함해서 원소를 생성
    - 세 번째 인자로 간격 대신 원소의 개수를 전달
        - 초기값은 50
    - 기본으로 실수를 가진 원소를 만듦

In [37]:
lin = np.linspace(1, 10, 10)
lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
lin.dtype

dtype('float64')

In [42]:
# 값의 간격을 표시하는 증분(incremental)을 확인할 수 있음
lin2 = np.linspace(1, 2, 10, retstep = True)
lin2

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 0.1111111111111111)

In [43]:
lin2[0].size

10

In [46]:
# 종료값을 제외할 수도 있음
lin3 = np.linspace(1, 10, 10, endpoint = False, retstep = True)
lin3

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

## 벡터의 크기 및 단위 벡터 구하기

- 선형대수의 벡터는 크기와 방향을 가짐
- 벡터의 크기는 노름(norm)이라고 부름
- 벡터는 평면좌표의 점을 표시하듯이 2개의 원소를 가진 것을 대표적으로 사용
    - 벡터의 크기는 피타고라스의 정리를 사용

### 벡터의 크기 계산

In [47]:
# 두 개의 원소를 가지는 1차원 배열 생성
v = np.arange(3, 5)
v

array([3, 4])

In [49]:
# 벡터의 크기를 구하기 위해 각 원소를 제곱하여 환산한 후 제곱근 계산
v_p = np.power(v, 2)
v_p

array([ 9, 16], dtype=int32)

In [50]:
v_r = np.sqrt(np.sum(v_p))
v_r

5.0

In [51]:
# 피타고라스의 정리를 구하는 hypot 함수를 사용할 수도 있음
np.hypot(v[0], v[1])

5.0

In [52]:
# 더 많은 원소를 가진 벡터의 크기를 구할때는 np.linalg.norm
np.linalg.norm(v)

5.0

### 단위 벡터(unit vector)

- 벡터의 크기가 항상 1인 경우를 단위 벡터라고 함
- 표준 단위 벡터(standard unit vector)는 원소 중에 하나가 1이고 나머지 원소가 0인 경우

In [53]:
# 표준 단위 벡터 예시
e1 = np.array([1, 0, 0])
np.linalg.norm(e1)

1.0

In [55]:
e2 = np.array([0, 1, 0])
np.linalg.norm(e2)

1.0

In [56]:
e3 = np.array([0, 0, 1])
np.linalg.norm(e3)

1.0

In [86]:
e4 = np.array([1/(2**(1/2)), 1/(2**(1/2)), 0])
np.linalg.norm(e4)

0.9999999999999999

- 일반적인 단위 벡터를 구할 때는 벡터의 크기를 구하고 각 원소를 벡터의 크기로 나누어서 구함

In [57]:
# 1차원 배열을 생성하고 이 배열의 크기를 계산
v_3 = np.array([1, 2, 3])
v_3

array([1, 2, 3])

In [58]:
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [60]:
v_3_u = v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [61]:
np.linalg.norm(v_3_u)

1.0

## 벡터 상등과 벡터간 거리

- 벡터의 상등(equality) : 벡터의 크기와 방향이 같은 경우
    - 크기는 같지만 방향이 다른 경우는 상등이 아님

In [62]:
# 두 벡터가 동일한 경우
a = np.arange(3, 5)
b = np.arange(3, 5)

In [63]:
np.array_equal(a, b)

True

In [64]:
a_1 = np.linalg.norm(a)
b_1 = np.linalg.norm(b)

In [65]:
a_1 == b_1

True

In [66]:
# 방향이 반대일 경우는 -1을 곱하여 방향을 바꿈
b_2 = -1 * np.linalg.norm(b)
b_2

-5.0

- 두 벡터의 거리는 두 벡터 간의 차를 계산한 후에 제곱을 합산한 후 제곱근 계산

In [67]:
# 두 개의 벡터인 1차원 배열을 생성
c = np.arange(10, 13)
d = np.arange(0 , 3)

In [68]:
c

array([10, 11, 12])

In [69]:
d

array([0, 1, 2])

In [73]:
np.sqrt(np.sum(np.square(c - d)))

17.320508075688775

In [74]:
# norm 함수에 두 벡터의 차를 인자로 전달하는 방법도 있음
np.linalg.norm(c - d)

17.320508075688775

# 행렬(matrix)

- 벡터는 하나의 차원이 축을 가져서 1차원 배열로 표시했지만 행렬은 두 개의 축인 차원을 가짐
    - 이 차원의 수평 방향을 행(row), 수직 방향을 열(column)이라고 함
- 보통 선형대수는 대괄호 내에 행과 열의 인덱스 위치에 숫자를 나열해서 표시
- 행렬을 부를 때는 보통 m개 행, n개 열로 이루어져서 m x n 행렬이라고 함

In [75]:
a = np.array([[43], [44]])
a

array([[43],
       [44]])

In [76]:
type(a)

numpy.ndarray

In [77]:
# a 변수에 저장된 것도 하나의 배열이므로 하나의 자료형을 가짐
a.dtype

dtype('int32')

In [78]:
# 배열의 차원 확인
a.ndim

2

In [79]:
# 형상 확인
# (행, 열)
a.shape

(2, 1)

In [80]:
# np.full(형상, 채워질 값, 자료형) : 다차원 배열의 원소의 값을 동일하게 채움
b = np.full((3, 4), 7, "int64")
b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int64)

## 행렬의 랭크

- 행렬은 두 개의 차원을 구성해서 행과 열로 구성함
- 행렬은 행을 기준으로 벡터를 쌓거나 열로 벡터를 쌓아서 만들어지는 구조
- 이 행렬 내의 벡터를 조합해서 다른 벡터를 만들 수 있는 경우를 제외한 벡터들의 수를 구하는 것을 행렬의 랭크 (matrix rank)라고 함

- 선형 독립 (linearly independent) : 어떤 벡터를 다른 벡터의 조합으로 만들 수 없는 유일한 상태
- 선형 종속 (linearly dependent) : 여러 벡터로 조합해서 만들 수 있는 상태

- 행렬의 랭크를 구하는 기준 : 행렬을 구성하는 행과 열벡터가 선형독립인 벡터인지 확인하는 것
- 행렬의 랭크를 구하는 방법 : 전체 벡터의 개수 - 선형 종속인 벡터의 개수
    - 행렬이 정사각형일 때는 최대 랭크는 행이나 열의 개수
    - 행렬이 직사각형일 때는 m x n 행렬에서 m > n 일때, 행렬의 랭크는 n보다 클 수 없음
        - r(A) <= min(m, n)

- 1차원 배열은 하나의 벡터이므로 무조건 선형 독립임

In [81]:
v1 = np.array([1, 2, 3, 4])

In [82]:
np.linalg.matrix_rank(v1)

1

- 2 x 3 행렬을 만든다면 최대 랭크의 수는 2보다 작거나 같아야함

In [84]:
c = np.array([[1, 2, 4], [2, 4, 8]])
c

array([[1, 2, 4],
       [2, 4, 8]])

In [85]:
np.linalg.matrix_rank(c)

1

- c 배열은 첫 번째 행에 2를 곱하면 두 번째 행이 만들어짐
    - 두 번째 행은 선형 종속
    - 선형 독립은 하나의 행만 있음